name: Create Readme
# masterブランチにpushされたときに実行
on:
  push:
    branches:
    - master
# 実行内容
jobs:
  create_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: create readme
      env:
        SRC_README_PATH: ./Assets/VRCAvatars3Tools/README.txt
        DST_README_PATH: ./.github/README.md
        EMAIL: ${{ secrets.EMAIL }} 
      run: |
        cp --force ${SRC_README_PATH} ${DST_README_PATH}
        sed -i -e 's/\n/  \n/g' ${DST_README_PATH}
        git config --global user.email ${EMAIL}
        git config --global user.name "gatosyocora"
        git add .
        git commit -m "update readme" && git push origin master || true
