name: Create Readme
# masterブランチにpushされたときに実行
on:
  push:
    branches:
    - master
# 実行内容
jobs:
  create_readme:
    runs-on: windows-lastest
    steps:
    - uses: actions/checkout@master

    - name: create readme
      env:
        SRC_README_PATH: ./Assets/VRCAvatars3Tools/README.txt
        DST_README_PATH: ./.github/README.md
        PS_FILE_PATH: ./.github/make_md.ps1 
        EMAIL: ${{ secrets.EMAIL }} 
      run: |
        Unblock-File %PS_FILE_PATH%
        powershell %PS_FILE_PATH% %SRC_README_PATH% %DST_README_PATH%
        git config --global user.email %EMAIL%
        git config --global user.name "gatosyocora"
        git add .
        git commit -m "update readme" && git push origin master || true
