name: Create Readme
# masterブランチにpushされたときに実行
on:
  push:
    branches:
    - master
# 実行内容
jobs:
  create_readme:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: create readme
      env:
        SRC_README_PATH: "./Assets/VRCAvatars3Tools/README.txt"
        DST_README_PATH: "./.github/README.md"
        PS_FILE_PATH: "./.github/make_md.ps1"
        EMAIL: ${{ secrets.EMAIL }} 
      run: |
        Unblock-File $env:PS_FILE_PATH
        powershell $env:PS_FILE_PATH $env:SRC_README_PATH $env:DST_README_PATH
        git config --global user.email $env:EMAIL
        git config --global user.name "gatosyocora"
        git add .
        # ファイルに変更がなかった場合エラーが出るのでechoでcatchする
        git commit -m "update readme" || echo "No changes to commit"
        git push origin master || echo "Everything up-to-date"
